/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : Tommy
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : SCOTT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2013-01-21 19:18:43
*/


-- ----------------------------
-- Table structure for "SCOTT"."T_CATALOGITEM_ARTICLE"
-- ----------------------------
DROP TABLE "SCOTT"."T_CATALOGITEM_ARTICLE";
CREATE TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" (
"ID" NUMBER(10) NOT NULL ,
"ARTICLEID" NUMBER(10) NOT NULL ,
"CATALOGITEMID" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of T_CATALOGITEM_ARTICLE
-- ----------------------------
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('1', '1', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('2', '2', '2');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('3', '3', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('4', '4', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('5', '5', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('6', '6', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('7', '7', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('8', '8', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('9', '9', '1');
INSERT INTO "SCOTT"."T_CATALOGITEM_ARTICLE" VALUES ('10', '10', '1');

-- ----------------------------
-- Checks structure for table "SCOTT"."T_CATALOGITEM_ARTICLE"
-- ----------------------------
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("ARTICLEID" IS NOT NULL);
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("CATALOGITEMID" IS NOT NULL);
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("ARTICLEID" IS NOT NULL);
ALTER TABLE "SCOTT"."T_CATALOGITEM_ARTICLE" ADD CHECK ("CATALOGITEMID" IS NOT NULL);
