Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (3,3,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (4,4,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (5,5,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (6,6,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (7,7,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (8,8,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (9,9,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (10,10,1);




commit;
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (1,1,1);
Insert into CATALOGITEMARTICLE (ID,ARTICLEID,CATALOGITEMID) values (2,2,null);
--' || '&' || '
